### ISSUE TITLE
exporting IDB into BinNavi built from first checkin

### ISSUE THREAD

**Issue by ShaneK2** [google/binnavi#3]
Just noticed your new check in, will reattempt with a new build. 

I was getting error exporting: executing query failed: ERROR: could not create unique index "ex_3_base_types_pkey" DETAIL: Key(id)=(822) is duplicated.

Is this known/resolved thanks.

**Comment by jksecurity** [comment]
I can confirm this issue.

**Comment by 0xFFFFFFFE** [comment]
I can unfortunately not reproduce the issue. I tested the checked in plugins. Can you provide some more details such that I am able to reproduce the error. Thanks.

**Comment by jksecurity** [comment]
@0xFFFFFFFE I can already provide you with the following details:
- OS: Windows 7 SP1 64bit
- PG: Postgres 9.4.4 64bit
- IDA: IDA Pro 6.8 32bit
- Target: Savant Web Server 3.1

I can provide you the actual IDB file later today if you would need it.

**Comment by 0xFFFFFFFE** [comment]
I have to correct myself (should not do so much late night hacking). The currently checked in exporter for windows is broken by a bug I introduced. This is already fixed in an upstream version, which I will check in soon. Ill close the bug as soon as this is done.

**Comment by matthiaskaiser** [comment]
Still not working. Pulled latest. Built under Linux. Run under Windows 8.1. Tried to import 32 bit kernel32.dll. Same Issue again.

**Comment by jksecurity** [comment]
I can confirm the issue is not fixed with the latest commit.

**Comment by cblichmann** [comment]
Alright, it should be fixed now. Didn't properly sync to the latest internal version. Tested both Windows and Linux.
Ah well, we (zynamics) are still figuring out how to properly do OSS :)

**Comment by matthiaskaiser** [comment]
Sorry. Got same issue:
Error exporting: executing query failed: ERROR: could not create unique index "ex1_base_types_pkey" DETAIL: Key (id)=(2112) is duplicated.

I did a fresh git clone.
Do you need a logfile? Or idb?

Thanks,
Matthias

**Comment by cblichmann** [comment]
IDB would be optimal. And optionally the SHA1 hash of your zynamics_binexport_8 plugin in your IDA directory. Which date does the plugin report in IDA's output window?
Do you also have BinDiff installed? If so, please overwrite its zynamics_binexport_8 plugin with the one from this repository.

**Comment by matthiaskaiser** [comment]
Got it finally working. Removed BinDiff. Deleted zynamics_binexport_8 files. Installed it again. Works!
Thanks for your support!

**Comment by 0xFFFFFFFE** [comment]
Cool thanks for checking that it now works.

Matthias Kaiser <notifications@github.com> schrieb am Di., 25. Aug. 2015 um
22:51 Uhr:

**Comment by cblichmann** [comment]
We'll also update BinDiff in a few days to contain the right plugin. Having both BinNavi and BinDiff is relatively common, after all.
